
export const INICIO_CARGANDO_PRODUCTO = 'INICIO_CARGANDO_PRODUCTO';
export const FIN_CARGANDO_PRODCUTO = 'FIN_CARGANDO_PRODCUTO';
export const SET_PRODUCTOS = 'SET_PRODUCTOS';
export const SET_SELECCIONAR_PRODUCTO = 'SET_SELECCIONAR_PRODUCTO';

export const INICIO_CARGANDO_OFERTA = 'INICIO_CARGANDO_OFERTA';
export const FIN_CARGANDO_OFERTA = 'FIN_CARGANDO_OFERTA';
export const SET_OFERTAS= 'SET_OFERTAS';
export const SET_SELECCIONAR_OFERTA = 'SET_SELECCIONAXR_OFERTA';

export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const SUMAR_PRODUCTO = "SUMAR_RPODUCTO";
export const RESTAR_PRODUCTO = "RESTAR_PRODUCTO";
export const ELIMINAR_TODO = "ELIMINAR_TODO";


export const INICIO_CARGANDO_CATEGORIA = 'INICIO_CARGANDO_CATEGORIA';
export const FIN_CARGANDO_CATEGORIA = 'FIN_CARGANDO_CATEGORIA';
export const SET_CATEGORIAS= 'SET_CATEGORIAS';
export const SET_SELECCIONAR_CATEGORIA = 'SET_SELECCIONAR_CATEGORIA';

export const SET_REGISTRO= 'SET_REGISTRO';
export const SET_ENTREGA= 'SET_ENTREGA';

export const INICIO_CARGANDO_LOGIN = "INICIO_CARGANDO_LOGIN";
export const FIN_CARGANDO_LOGIN = "FIN_CARGANDO_LOGIN";
export const SET_SUCCESS_LOGIN = "SET_SUCCESS_LOGIN";
export const SET_CERRAR_LOGIN = "SET_CERRAR_LOGIN";

export const INICIO_CARGANDO_VENTAS = "INICIO_CARGANDO_VENTAS";
export const FIN_CARGANDO_VENTAS = "FIN_CARGANDO_VENTAS";
export const SET_VENTAS = "SET_VENTAS";
